nurse/nurse_registration/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired, length, Email


class registration_form(FlaskForm):
    email = StringField("ელექტრონული ფოსტა", [DataRequired(), length(min=4), Email()])
    first_name = StringField("სახელი", [DataRequired()])
    last_name = StringField("გვარი", [DataRequired()])
    submit = SubmitField("Done")


class registration_form2(FlaskForm):
    address = StringField("მისამართი", [DataRequired()])
    department = StringField("დეპარტამენტი", [DataRequired()])
    shift = SelectField("მორიგეობის განრიგი:",
                        choices=[
                            (16, "16 საათიანი მორიგეობა"),
                            (24, "24 საათიანი მორიგეობა"),
                            {8, "დღის სამსახური"}
                        ])
    submit = SubmitField("Done")


class final_save_to_db(FlaskForm):
    submit = SubmitField("Save")

nurse/nurse_registration/views.py
from flask_login import login_required, current_user
from nurse import db, NursesModel
from flask import render_template, redirect, url_for, session, Blueprint
from nurse.nurse_registration.forms import registration_form, registration_form2, final_save_to_db


nurse_blueprint = Blueprint('nurse_registration',
                            __name__,
                            template_folder='templates/nurse_registration')


@nurse_blueprint.route('/step1', methods=['GET', 'POST'])
@login_required
def step1():
    email = None
    first_name = None
    last_name = None

    form = registration_form()

    if form.validate_on_submit():
        session['email'] = form.email.data
        session['first_name'] = form.first_name.data
        session['last_name'] = form.last_name.data
        return redirect(url_for('nurse_registration.step2'))

    return render_template("home.html", form=form, email=email, first_name=first_name, last_name=last_name)


@nurse_blueprint.route('/step2', methods=['GET', 'POST'])
@login_required
def step2():
    address = None
    department = None
    shift = None

    form = registration_form2()

    if form.validate_on_submit():
        session['address'] = form.address.data
        session['department'] = form.department.data
        session['shift'] = form.shift.data

        return redirect(url_for('nurse_registration.validation'))

    return render_template("step2.html", form=form, address=address, department=department, shift=shift)


@nurse_blueprint.route('/validation', methods=['GET', 'POST'])
@login_required
def validation():
    form = final_save_to_db()

    if form.validate_on_submit():
        print(form.errors)
        new_nurse = NursesModel(current_user.get_id(), session['email'], session['first_name'], session['last_name'],
                                session['address'], session['department'], session['shift'])
        db.session.add(new_nurse)
        db.session.commit()

        return redirect(url_for('homepage.representation'))

    return render_template('validation.html', form=form)

nurse/nurse_registration/templates/nurse_registration/home.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>


    <div class="container"><br>
      <center>
        <h2>რეგისტრაციის ფორმა</h2>
      </center>
    </div>

<div class="well form-horizontal">
    <div class="row align-items-center justify-content-center">
    <div class="col-md-5">

    {% if email %}
        <p> თქვენ მოგივათ შეტყობინებები მისამართზე: {{ email }} </p>
        <p> თქვენი სახელია: {{ first_name }} {{ last_name }} </p>
    {% else %}
        <p> გთხოვთ შეავსოთ </p>
    {% endif %}
    <form method="POST" class="form-group" >
        <div class="form-group">
        {{ form.hidden_tag() }}
         {{ form.email.label }} {{ form.email(class_="form-control") }}
         {{ form.first_name.label}} {{ form.first_name(class_="form-control") }}
         {{ form.last_name.label }} {{ form.last_name(class_="form-control") }}
        <br>
        {{ form.submit(class_="btn btn-primary mb-2") }}
    </form>
        </div>
        </div>
</div>
</body>

{% endblock %}

nurse/nurse_registration/templates/nurse_registration/step2.html
{% extends 'base.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>


    <div class="container"><br>
      <center>
        <h2>რეგისტრაციის ფორმა</h2>
      </center>
    </div>

<div class="well form-horizontal">
    <div class="row align-items-center justify-content-center">
    <div class="col-md-5">
    <form method="POST" class="form-group" >
        <div class="form-group">
         {{ form.hidden_tag() }}
         {{ form.address.label }} {{ form.address(class_="form-control") }} <br>
         {{ form.department.label}} {{ form.department(class_="form-control") }} <br>
         {{ form.shift.label }} {{ form.shift() }} <br> <br>
         {{ form.submit(class_="btn btn-primary mb-2") }} <br>
         </div>
    </form>

    </div>
</div>
</div>
</body>

{% endblock %}

nurse/nurse_registration/templates/nurse_registration/validation.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>

<div class="container-sm">
    <table class="table table-striped">
        <tr>
            <th>პარამეტრი</th>
            <th>მონაცემი</th>
            <th>მოქმედება</th>
        </tr>
        <tr>
            <th>ელექტრონული ფოსტა</th>
            <th>{{session['email']}}</th>
            <th><a href={{url_for('nurse_registration.step1')}}>რედაქტირება</a></th>
        </tr>
        <tr>
            <th>სახელი</th>
            <th>{{session['first_name']}}</th>
            <th><a href={{url_for('nurse_registration.step1')}}>რედაქტირება</a></th>
        </tr>
        <tr>
            <th>გვარი</th>
            <th>{{session['last_name']}}</th>
            <th><a href={{url_for('nurse_registration.step1')}}>რედაქტირება</a></th>
        </tr>
        <tr>
            <th>დეპარტამენტი</th>
            <th>{{session['address']}}</th>
            <th><a href={{url_for('nurse_registration.step2')}}>რედაქტირება</a></th>
        </tr>
        <tr>
            <th>მისამართი</th>
            <th>{{session['department']}}</th>
            <th><a href={{url_for('nurse_registration.step2')}}>რედაქტირება</a></th>
        </tr>
        <tr>
            <th>მორიგეობის განრიგი</th>
            <th>{{session['shift']}}</th>
            <th><a href={{url_for('nurse_registration.step2')}}>რედაქტირება</a></th>
        </tr>
    </table>
    </div>
<div class="col-md-12 text-center">
<form method="POST" class="container">
    {{ form.hidden_tag() }}
    {{ form.submit(class_="btn btn-primary mb-2") }}
</form>
</div>
</body>

{% endblock %}