nurse/homepage/views.py
from flask import render_template, Blueprint

homepage = Blueprint('homepage',
                     __name__,
                     template_folder='templates/homepage')


@homepage.route('/', methods=['GET'])
def representation():
    return render_template("represent.html")

nurse/homepage/templates/homepage/base.html
<head>
    <meta charset="UTF-8">
    <title>Nursera</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Nursera</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <a class="nav-item nav-link" href="{{ url_for('homepage.representation') }}">თავფურცელი</a>
        {% if current_user.is_authenticated %}
        <a class="nav-item nav-link" href="{{ url_for('user.user_profile') }}">პროფილი</a>
        <a class="nav-item nav-link" href="{{ url_for('logout') }}">გამოსვლა</a>
        {% else %}
        <a class="nav-item nav-link" href="{{ url_for('user.login') }}">შესვლა</a>
        <a class="nav-item nav-link" href="{{ url_for('user.new_user_registration') }}">რეგისტრაცია</a>
        {% endif %}
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}

<script
  src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
  crossorigin="anonymous"
></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
  crossorigin="anonymous"
></script>
<script
  src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
  crossorigin="anonymous"
></script>
</body>
</html>

nurse/homepage/templates/homepage/represent.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Start registration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>

<div class="container my-3">
    <div class="col-md-12 text-center">
    {% if current_user.is_authenticated %}
        <a href={{url_for('nurse_registration.step1')}}>
         <button type="button" class="btn btn-primary">შეიყვანე პირადი ინფორმაცია</button>
        </a>
    {% endif %}

    </div>

<br> <br> <br> <br>

<div class="col-md-12 text-center">
        {% if current_user.is_authenticated %}
        გამარჯობა {{ current_user.username }}
        {% else %}
        გთხოვთ დარეგისტრირდეთ საიტზე
        {% endif %}
</div>

</body>

{% endblock %}